### ISSUE TITLE
Automatically correct username capitalization

### ISSUE THREAD

**Issue by psikoi** [psikoi/wise-old-man#123]
Extension of #45 

Since we are currently formatting all usernames "To Be Like This", a lot of people with custom usernames aren't happy.

A suggestion that has been discussed before on discord is to use the hiscores leaderboard pages to check the correct capitlization for any given name. (Because names are correctly capitalized in those pages for some reason).

The only way that we're currently aware of to do this, is to fetch the contents of this page:

`https://secure.runescape.com/m=hiscore_oldschool/overall?table=0&user=lynx%A0titan`

Find the correct table row by checking a name match:
`lowercase(tableUsername) === lowercase(databaseUsername)`

Or by checking the row's color (it seems to be red)

The question now is:

Would this be another endpoint in the players module, or an automatic check onPlayerUpdate?(maybe with a time limit, like once every 24h)

PS: With this, some other endpoints on the API have to be changed to support unstandardized usernames.

**Comment by psikoi** [comment]
Edit: changed to a much easier approach (using a more direct URL) thanks to @Knutakir 's suggestion on discord

**Comment by psikoi** [comment]
![image](https://user-images.githubusercontent.com/3278148/81929484-fe4da080-95de-11ea-87fc-26863dab1c1a.png)

**Comment by dekvall** [comment]
It seems easiest to grab the correct name with something like this
```
name="lynx titan" && curl -s "https://secure.runescape.com/m=hiscore_oldschool/overall?table=0&user=$name" | sed 's/\xa0/ /g' | grep -ioP "user1=\K$name"
```
I think that this should be handled exactly like ironman type checking, so if we check this on name change we should probably also check ironman status on name change
