### ISSUE TITLE
Sortable Tables for Player Pages

### ISSUE THREAD

**Issue by CubeLuke** [psikoi/wise-old-man#136]
For all tables that would make sense, there should be some form of client-side sorting. Tables such as on a player profile, the ability to sort the skilling/bossing/activities tables. Something kinda simple such as clicking the table header to toggle between an ascending/descending should suffice.

**Comment by psikoi** [comment]
This has been suggested before, I actually thought this was a duplicate issue, but it doesn't seem to be! Thank you

**Comment by psikoi** [comment]
Implemented in #139
