### ISSUE TITLE
Giving a number for metric in the competition create call gives a bad error message

### ISSUE THREAD

**Issue by MathieuDR** [psikoi/wise-old-man#157]
When you send an integer for the metric field at creating a competition you'll get the following error
`metric.toLowerCase is not a function`

Request body

```json
{
   "title":"Fanatic granite sprint",
   "metric":16,
   "groupVerificationCode":"<VALIDTOKEN>",
   "groupId":51,
   "startsAt":"2020-05-25T22:00:00.000Z",
   "endsAt":"2020-05-30T22:00:00.000Z"
}
```

**Comment by hjdarnel** [comment]
It looks like the `metric` field only supports a string of an enumerated value. See the docs here: https://wiseoldman.net/docs/competitions

Seems like there's no bug here.

**Comment by breeku** [comment]
Should the error message reflect that? 
[https://github.com/psikoi/wise-old-man/blob/master/server/src/api/modules/competitions/competition.service.js#L245](https://github.com/psikoi/wise-old-man/blob/master/server/src/api/modules/competitions/competition.service.js#L245)

**Comment by MathieuDR** [comment]
Yeah I know it's only a string, just meant that the error message should give a different error message. Eg type incorrect or request failed or something like that.

**Comment by psikoi** [comment]
`competition.service.js` line 250 is:

```
if (!metric) {
    throw new BadRequestError('Invalid competition metric.');
}
```

should maybe be

```
if (!metric || !ALL_METRICS.include(metric)) {
    throw new BadRequestError('Invalid competition metric.');
}
```
