### ISSUE TITLE
Unable to ctrl-click homescreen buttons

### ISSUE THREAD

**Issue by TimvdLippe** [psikoi/wise-old-man#52]
The homescreen buttons are not ctrl-clickable, as they are not actually `<button>`s: 
![image](https://user-images.githubusercontent.com/5948271/80871571-4b5b7980-8ca5-11ea-809d-01cafa8ebd64.png)

I expect that `ctrl + click` opens the link in a new tab, rather than changing the URL in the current tab.

**Comment by TimvdLippe** [comment]
Now that I think of it, you probably want to use a `<a>` instead, as they are links, not buttons. You should be able to style a `<a>` in a similar way to what you have now.

**Comment by psikoi** [comment]
Yea I'll change that, I was just using a <Button> component because it delays the clicks by a like 300ms, while displaying an animation. This makes the UI feel nicer to the "touch" but I can certainly improve that, thank you

**Comment by TimvdLippe** [comment]
Given that these parts are for navigation, as a user I would not expect an animation. That's my personal preference, but it is my hunch that others prefer that behavior as well. You could still add an animation on a `<a>` and use `animationend` to trigger the actual navigation.

**Comment by psikoi** [comment]
Sounds good, will do!

**Comment by TimvdLippe** [comment]
Btw the same is true for navigation links on https://wiseoldman.net/records where I would expect to ctrl-click on the "shh" link. Are they using the same button implementation? If so, then they would be fixed as well 😄

**Comment by psikoi** [comment]
Yea.. I'm doing something similar :( Gotta do a little overall navigation improvement it seems

**Comment by ClumsyPenguin** [comment]
did it allready, i wrapped your button tags around an a tag. https://github.com/psikoi/wise-old-man/pull/63

**Comment by psikoi** [comment]
Although the homepage buttons are fixed, I'm leaving this issue up as there are other places throughout the app where this behaviour still exists.

I'll try and get to them all within the next day or so.
