### ISSUE TITLE
Unable to load group 1 - 504 on api/groups/1

### ISSUE THREAD

**Issue by Jbradd72** [psikoi/wise-old-man#54]
Loading https://wiseoldman.net/groups/1 results in a loading screen that stays for quite a while and then eventually redirects to the 404 page. The api/groups/1 request is returning a 504

![image](https://user-images.githubusercontent.com/22182923/80873461-4f27d580-8c7e-11ea-9fd8-fa0dd7ec79ff.png)

![image](https://user-images.githubusercontent.com/22182923/80873474-6070e200-8c7e-11ea-99da-ac618d813a0b.png)

![image](https://user-images.githubusercontent.com/22182923/80873485-7d0d1a00-8c7e-11ea-853e-885abec57af1.png)

**Comment by psikoi** [comment]
Yea the server is overloading right now, I'm working on upgrading it as we speak, thanks!

**Comment by psikoi** [comment]
Fixed in #62
