### ISSUE TITLE
Display All Offending Names when Creating/Editing Group

### ISSUE THREAD

**Issue by Bonfire** [psikoi/wise-old-man#59]
Currently, when importing a list of names to create or edit a group, and there is a name that does not conform to name requirements (length, symbols, etc.), the user is presented with an error saying that the list of names could not be imported correctly.

I propose an enhancement to this error message showing all of the names that are causing the error to be thrown.

This can be done in the form of a separate notification that pops up, an addition to the current error message, or by highlighting names on the name list that don't meet the requirements. This would assist group leaders in making sure their names fit the requirements, and knowing exactly which names don't.

**Comment by Jakesterwars** [comment]
I've started looking into this. Currently have it spitting out the bad names to the error message, but I'm investigating a cleaner way to display the bad names and name requirements.

**Comment by Jakesterwars** [comment]
#85 Backend PR for this issue. Still needs front end work to highlight the users in the list.

**Comment by Jakesterwars** [comment]
#110 Has the backend portion completed, closed #85 for it. Front-end needs the work still.
