### ISSUE TITLE
Being able to click on a skill in a player's Gained tab to show the graph of that skill

### ISSUE THREAD

**Issue by Hydrox6** [psikoi/wise-old-man#76]
Currently, to change the graphs on the Gained tab, you have to navigate a dropdown. It would be really nice to use if the user could click on a skill in the table below to view that graph.

**Comment by psikoi** [comment]
Should be easy with the `Table`'s onRowClicked event, good for firsr contribution. Thanks

**Comment by psikoi** [comment]
Implemented in #73
