### ISSUE TITLE
API: Group negative overall exp

### ISSUE THREAD

**Issue by psikoi** [psikoi/wise-old-man#82]
As overallExperience defaults to -1, when we create a new group, it will sum everyone's overallExperience and eventually return a negative number.

![image](https://user-images.githubusercontent.com/3278148/81131118-00aa5d80-8f42-11ea-82d8-4314fb3b4520.png)

**Comment by ClumsyPenguin** [comment]
why does it default to -1 in the first place? you can fix this to put "Unknown" when the frontend gets a number lower than zero.

**Comment by psikoi** [comment]
Snapshots' exp/rank values are -1 by default (for unknown), so if there's a team of 100 and they all have -1 overallExp, the total exp becomes -100, this should be a quick fix, probs 1 line.

 `Math.max(0, overallExp)`

**Comment by ClumsyPenguin** [comment]
#86

**Comment by psikoi** [comment]
Fixed.
