### ISSUE TITLE
Competition/Group import list clearing manual names

### ISSUE THREAD

**Issue by psikoi** [psikoi/wise-old-man#90]
When we import a list in comp/group edit/create, it overrides whatever names were already manually inserted.

**Comment by dekvall** [comment]
This sounds like more of a feature than a bug, since clans probably keep a clan roster which can be easily exported to txt. It makes removing inactive players easier, and you won't have to edit two lists manually. At least it should be kept as an option imo.

**Comment by Jakesterwars** [comment]
A toggle on the modal while importing could be utilized here to keep the "bug" and what @dekvall suggested.

**Comment by psikoi** [comment]
Thats true, it would be nice to have a override toggle
