### ISSUE TITLE
XP Drop and Earliest indicators

### ISSUE THREAD

**Issue by psikoi** [psikoi/wise-old-man#91]
On the player's gained tab, show the date of the earliest snapshot in the selected period. And also show how long before the next xp drop.

Xp drop is 24h - timeago(earliest)

**Edit: this is a frontend change, as the necessary data is already given through the API.**

**Comment by dabolink** [comment]
should be based off the current view (day, week, month, year) - timeago(earlies)

**Comment by psikoi** [comment]
"in the selected period" that's what I meant, but thanks for clarifying!
