### ISSUE TITLE
Add the ability to link to specific sections on pages

### ISSUE THREAD

**Issue by Hydrox6** [psikoi/wise-old-man#95]
Scenario: I've been grinding out some hella Runecrafting, and I want to share it with my friends. At the moment, I am unable to send them directly to the section, and instead have to assume that if I tell them, they'll actually look at the correct place.

Probably by utilising `#` links, it could be possible to at least link someone to the correct tab, maybe with some GET params you could pre-select stuff, eg. `Skill` and `Period` in the `Gained` tab.

Competition pages also have a second tab for top 10 gains, and the Records page also has selections for account type and skill.

Example:
`https://wiseoldman.net/players/1124#gained?skill=runecrafting&period=year`
Might be a bit clunky
`https://wiseoldman.net/players/1124#gained?s=17&p=y`
17 being the (probably incorrect) index of Runecrafting in a list I think probably exists somewhere on the site already

**Comment by psikoi** [comment]
Nice, I like this, shouldn't be too hard!

**Comment by psikoi** [comment]
> Nice, I like this, shouldn't be too hard!

It was
